import { Test } from '@/widgets/test/Test'
import Head from 'next/head'

import '@leetvin/ui-kit/dist/style.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>

      <main>
        <Test />
      </main>
    </>
  )
}
